### ISSUE TITLE
Plot waveforms 

### ISSUE THREAD

**Issue by liesenf** [elpaco-escience/talkr#94] opened 2024-08-21 11:35 UTC
Once scikit-talk supplies this functionality, including audio data in the plots becomes within reach:

**Description:**
the idea is that `talkr` can utilise the [audio] column in the data frame to print waveforms into the boxes in the plot, similar to how  text transcripts are currently rendered.

**Comment by bvreede** [comment] 2024-08-21 11:56
This is related to https://github.com/elpaco-escience/scikit-talk/issues/23

**Comment by mdingemanse** [comment] 2024-08-21 21:00
Closing as duplicate of #46 but taking note of Barbara's ref to the scikit-talk issue

**Closed by mdingemanse** 2024-08-21 21:00 UTC
Labels: enhancement
